# Site settings
title: Tyler J Roberts
tag_text: tyler.engineering
description: Tyler Roberts' professional website.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
    style: compressed
